### PR TITLE
CPU-62 - Add support for multibranch pipeline

### PR DESCRIPTION
**Pull request by mattdrees**
implements https://jira.cru.org/browse/CPU-62

### CODE REVIEW

**Comment by mattdrees** [comment]
Hey Daniel, I think you've done at least a little python. Would you be up for looking this over?

It's ok if you can't dig deep.

**Comment by frett** [comment]
I'll take a look before EOD

**Review by frett — APPROVED** [review]
I don't have much experience with python, but it looks good to me

**Comment by mattdrees** [comment]
Yeah, I don't think many around Cru do. Mike and David H have dabbled with it, since it's what Ansible uses. But I don't think they're comfortable with it.

Thanks for the review!

**Pull request merged**
