### PR TITLE
CPU-62 - Upgrade modifications for cru jenkins to 2.0.1

### PR DESCRIPTION
**Pull request by mattdrees**
This is a rebase, plus fixes, of the current 'modifications-for-cru-jenkins' branch onto the 2.0.1 tag from openstack.

For work towards https://jira.cru.org/browse/CPU-62.

### CODE REVIEW

**Comment by mattdrees** [comment]
@mikealbert I'd like to do a force push to update 'modifications-for-cru-jenkins` to this commit (3e7ad96). Effectively, I'd like to deploy this PR. OK with you?

**Comment by mikealbert** [comment]
Sounds good to me.

**Comment by mattdrees** [comment]
thanks Mike!

**Comment by mattdrees** [comment]
done

**Pull request merged**
